### ISSUE TITLE
make dies in brown_grammar.o

### ISSUE THREAD

**Issue by roycewilliams** [lakiw/pcfg_cracker#1]
Platform:

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

$ uname -a
Linux irongiant 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:32:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ g++ --version | head -1
g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2

$ make --version | head -1
GNU Make 3.81

Error:

$ make
[snip]
g++  -c pcfg_manager.cpp
g++  -c tty.c
g++  -c brown_grammar.cpp
brown_grammar.cpp: In function 'int orderPointers(std::deque<ntGenTopStruct>_, std::deque<ppPointerStruct>_)':
brown_grammar.cpp:532:63: error: 'sort' was not declared in this scope
   sort(phraseList->begin(),phraseList->end(),compare_ppPointer);
                                                               ^
brown_grammar.cpp: In function 'int load_all_dics(std::deque<ntGenTopStruct>_)':
brown_grammar.cpp:729:85: error: 'sort' was not declared in this scope
     sort(phraseValues->at(i).data.begin(), phraseValues->at(i).data.end(), ntCompare);
                                                                                     ^
brown_grammar.cpp: In function 'int load_passphrase_grammar(pqueueType_, std::list<pqReplacementStruct>_, std::deque<ppPointerStruct>_, std::string, double)':
brown_grammar.cpp:806:9: error: 'transform' is not a member of 'std'
         std::transform(tempLine.begin(), tempLine.end(),tempLine.begin(), ::toupper);
         ^
make: **\* [brown_grammar.o] Error 1

**Comment by lakiw** [comment]
Thanks for finding this out. Sorry it took me two months to respond... I suspect I know what the problem is and hopefully I can fix it with a simple include statement.  The long term goal will be to rip out the passphrase stuff, (which the brown_grammar was a part of), as it didn't fit in well with the traditional pcfg_cracker.

**Comment by roycewilliams** [comment]
No problem at all!  If I had been in a big rush, I would have mentioned it more vigorously. ;)

**Comment by lakiw** [comment]
Matlink submitted a fix in pull request https://github.com/lakiw/pcfg_cracker/commit/760cdc57eebaa2d7eb3c415e741670af1ce457b6 so please send all thanks that way.
