### ISSUE TITLE
Use more than one rulesets

### ISSUE THREAD

**Issue by EvgeniaPatsoni** [lakiw/pcfg_cracker#17]
I was wondering if it is possible to use multiple rulesets when running a password strength scoring session. For example` -r ruleset1,ruleset2`

**Comment by lakiw** [comment]
I apologize in taking so long to reply to this. The short answer is not easily, but there are a couple of work-arounds.
1)  You can run the same password through the scorer multiple times, each time using a different rulset. 
2)  You can generate/train a ruleset on all the passwords in ruleset1 and ruleset2 to create a merged ruleset

Both options have pluses and minuses, and the approach you take really depends on what you are aiming for. If you want to see how a password scores against different target demographics, than option #1 is better. If you are looking at expanding your rulesets to cover a wider range of users, than #2 might be a better approach. The challenge with #2 is that depending on the relative training password sizes, one can overwhelm the other so there is a bit of alchemy still when creating an effective ruleset.

I hope this is helpful.

**Comment by lakiw** [comment]
Unless you have further questions, comments or suggestions I'm going to close this for now. Feel free to re-open it if you feel the options I listed are not adequate. Thanks for the interest you have shown in this tool!
