### ISSUE TITLE
Error in pcfg_trainer, no file or directory Grammar

### ISSUE THREAD

**Issue by Abelarm** [lakiw/pcfg_cracker#2]
IOError: [Errno 2] No such file or directory: './Rules/test/Grammar/Grammar.txt'

Solved:
OLD line 549: make_sure_path_exists('./Rules/'+'/Grammar')
NEW line 549: make_sure_path_exists('./Rules/'+ruleName+'/Grammar')

**Comment by lakiw** [comment]
Thanks for finding that! Finally getting back to this project so I fixed it as you recommended.
