### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by kevtheskin** [lakiw/pcfg_cracker#22]
Hi there, Can someone tell me how to run these tools in windows 10 please. I have python3 installed but dont know how to run the tool then pipe to hashcat. Cheers Kev

**Comment by lakiw** [comment]
Sure! Running it on Windows 10 vs. Linux should be exactly the same. If you open up a command prompt, (I've had powershell be "wonky" when it comes to pipeing output unless you are running windows subsystem for linux), you can run the following command

python C:\github\pcfg_cracker\pcfg_guesser.py | .\hashcat64.exe .\example0.hash

From the PCFG side, the commands are the same regardless of what operating system you are running it on.

You should quickly start cracking the hashcat test hashes with the default pcfg ruleset. For example, here is the output I got on my computer

Starting attack in stdin mode...

Starting to generate password guesses
Press [ENTER] to display a status output
Press 'q' [ENTER] to exit
8739cf0625b1b82b2ec681cc9c8aef26:shivava
07e9898c85d970341f26cada3dc7e038:2football
a08c354f925b2a9df839290c8903c1e9:dodge15
3567eb16b450397818bbda8a59a3993e:leigh99
b5d7e9ac2c5fcb7825e503213c24f7b6:teiubesc16
