### ISSUE TITLE
Add functionality of limiting the output

### ISSUE THREAD

**Issue by Wineh** [lakiw/pcfg_cracker#33]
Add limit option which makes the pcfg_guesser to exit when limit is reached. For generation of predetermined amount of results.

**Comment by lakiw** [comment]
Thank you so much once again for opening the issue as well as the pull request. It's been merged in with Main. If you have any problems with it, feel free to reopen this issue or create a new one.

**Comment by Wineh** [comment]
Cool, thanks for such a fast merge!
