### ISSUE TITLE
Error in module password_scorer.py

### ISSUE THREAD

**Issue by kart61** [lakiw/pcfg_cracker#43]
Hello.
You can ask to check the password_scorer.py module.

When executing the command from the instruction "python3 password_scorer -r NEW_RULESET -i INPUT_LIST", an error is displayed:

Version: 4.4
Loading Rule: /home/toor/Downloads/pcfg_cracker-master/MyRules/17
Initializing Multi-Word Detector
Initializing the OMEN scorer
Traceback (most recent call last):
 File "/home/toor/Downloads/pcfg_cracker-master/password_scorer.py", line 273, in <module>
 main()
 File "/home/toor/Downloads/pcfg_cracker-master/password_scorer.py", line 240, in main
 program_info['prefixcount'])
 ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'prefixcount'

If you exclude the 'prefixcount' parameter in password_scorer.py
file_input = TrainerFileInput(
 program_info['input_file'],
 pw_parser.encoding)#,
 #program_info['prefixcount'])

Then an error like this appears:
Version: 4.4

Loading Rule: /home/toor/Downloads/pcfg_cracker-master/MyRules/17
Initializing Multi-Word Detector
Initializing the OMEN scorer
Processing input wordlist

Traceback (most recent call last):
 File "/home/toor/Downloads/pcfg_cracker-master/password_scorer.py", line 254, in main
 result = pw_parser.parse(input_value)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/toor/Downloads/pcfg_cracker-master/lib_scorer/pcfg_password_scorer.py", line 167, in parse
 omen_score = self.omen.parse(password)
 ^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/toor/Downloads/pcfg_cracker-master/lib_scorer/omen_scorer.py", line 75, in parse
 pass_len = len(password)
 ^^^^^^^^^^^^^
TypeError: object of type 'generator' has no len()
Exception: object of type 'generator' has no len()
Exiting...

**Comment by lakiw** [comment]
I’m currently traveling so it’ll likely be a couple weeks before I can investigate this problem, but I wanted to take the time to thank you for reporting this issue. I really appreciate it, as reports like this are super helpful as I want to make these tools usable for researchers like you. I’ll update this issue when I am back home and can look into this, and thanks again!

**Comment by lakiw** [comment]
It's been a month, so I'm just getting back to you that I haven't forgotten this issue even though I haven't had a chance to look into it yet. Thank you again for submitting this and I'll eventually get to it!

**Comment by kart61** [comment]
Thank you so much for not forgetting.

I look forward to the update.

**Comment by lakiw** [comment]
Sorry about taking so long to fix this problem. Long story short, a previous feature changed how training passwords were read in and processed to support adding a prefix count to passwords in the training set. This totally broke the pcfg_scorer and I didn't catch it. Longer term I need to add some unittests for pcfg_scorer so I'll hopefully catch issues like this in the future.

Thank you so much for raising this issue, as well as being patient about my slow responses to it.
