### ISSUE TITLE
pcfg_guesser.py module, run on Windows

### ISSUE THREAD

**Issue by kart61** [lakiw/pcfg_cracker#45]
Hello.
You can ask to check the functionality of the pcfg_guesser.py module under Windows in order to be able to generate results and send them further along the pipeline.
There are no errors at startup, execution just ends immediately, either with built-in rules or with your own:
"
Version: 4.6

Loading Ruleset: Default

Exiting
"
In OS Linux everything works well, but you have to upload the results to a file first, which is not very convenient.

**Comment by kart61** [comment]
Yes, this solution helps.
Thank you.

**Comment by lakiw** [comment]
Lots of thanks to @0xVavaldi for the quick and effective fix. My apologies for taking so long to review it and approve the merge. Also thank you @kart61 for finding and pointing out the problem!!!!

Since the fix is now merged in with the main code, I'm closing this issue.
